- name: setup roboshop project
  hosts: all
  become: yes
  tasks:
    - name: Import frontend
      ansible.builtin.import_role:
        name: frontend
      tags: frontend
      when: APP == "frontend"

    - name: Import catalogue
      ansible.builtin.import_role:
        name: catalogue
      tags: catalogue
      when: APP == "catalogue"

    - name: Import mongodb
      ansible.builtin.import_role:
        name: mongodb
      tags: mongodb
      when: APP == "mongodb"

    - name: Import cart
      ansible.builtin.import_role:
        name: cart
      tags: cart
      when: APP == "cart"

    - name: Import user
      ansible.builtin.import_role:
        name: user
      tags: user
      when: APP == "user"

    - name: Import redis
      ansible.builtin.import_role:
        name: redis
      tags: redis
      when: APP == "redis"

    - name: Import mysql
      ansible.builtin.import_role:
        name: mysql
      tags: mysql
      when: APP == "mysql"

    - name: Import shipping
      ansible.builtin.import_role:
        name: shipping
      tags: shipping
      when: APP == "shipping"

    - name: Import payment
      ansible.builtin.import_role:
        name: payment
      tags: payment
      when: APP == "payment"

    - name: Import rabbitmq
      ansible.builtin.import_role:
        name: rabbitmq
      tags: rabbitmq
      when: APP == "rabbitmq"



