- name: setup roboshop project
  hosts: all
  tasks:
    - name: Import frontend
      ansible.builtin.import_role:
        name: frontend
      when: APP == "frontend"
    - name: Import catalogue
      ansible.builtin.import_role:
        name: catalogue
      when: APP == "catalogue"