- name: Demo on rumtime variables
  hosts: all
  tasks:
    - name: grab uptime
      shell: uptime
      register: out

    - name: print uptime
      debug:
        msg: "{{out.stdout}}"
    - name: set a vriable
      set_fact:
        UPTIME_OUTPUT: "{{out.stdout}}"

    - name: print uptime variable
      debug:
        msg: "{{UPTIME_OUTPUT}}"
