- name: demo on play variables
  hosts: all
  vars:
    URL: play.devopsproject.tk
  tasks:
    - debug:
        msg: URL = {{ URL }}

- name: demo on task level variables
  hosts: all
  tasks:
    - name: Print URL
      vars:
        URL: tasks.devopsproject.tk
      debug:
        msg: URL = {{ URL }}

- name: demo on cli variables
  hosts: all
  tasks:
    - name: print on cli
      debug:
        msg: URL1 = {{ URL1 }}
