- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: present


- name: Download {{ component }} component
  include_role:
    name: common
    tasks_from: curl_download
  vars:
    URL: "https://github.com/roboshop-devops-project/frontend/archive/main.zip"
    EXTRACT_DIR: /usr/share/nginx
    COMPONENT_DIR: /usr/share/nginx/html
    APP_USER: root

#- name: Download {{ component }} component
#  include_role:
#    name: common
#    tasks_from: nexus_download
#  vars:
#    URL: "http://172.31.71.110:8081/repository/frontend/frontend-1.0.{{APP_VERSION}}.zip"
#    EXTRACT_DIR: /usr/share/nginx/html
#    COMPONENT_DIR: /usr/share/nginx/html
#    APP_USER: root
#    ARCHIVE_FILE: "{{component}}.zip"


- name: move localhost.conf to roboshop.conf
  template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf
    remote_src: yes

- name: start nginx service
  systemd:
    name: nginx
    state: restarted

- name: setup prometheus
  include_role:
    name: common
    tasks_from: node_exporter
