- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: present


- name: Download {{ APP }} component
  include_role:
    name: common
    tasks_from: curl_download
  vars:
    URL: "https://dev.azure.com/DevOps-Batches/e869c1fe-489d-4f58-b676-fb75fe4e9e12/_apis/git/repositories/18fbb315-ed99-4a65-9b79-e7eec2f3e1b1/items?path=%2F&versionDescriptor%5BversionOptions%5D=0&versionDescriptor%5BversionType%5D=0&versionDescriptor%5Bversion%5D=master&resolveLfs=true&%24format=zip&api-version=5.0&download=true"
    EXTRACT_DIR: /usr/share/nginx/html

- name: move HTDOCS file
  shell: mv /usr/share/nginx/html/static/* /usr/share/nginx/html/.

- name: start nginx service
  systemd:
    name: nginx
    state: restarted