- name: Install nginx
  ansible.builtin.yum:
    name: nginx
    state: present


- name: Download {{ component }} component
  include_role:
    name: common
    tasks_from: curl_download
  vars:
    URL: "https://github.com/roboshop-devops-project/frontend/archive/main.zip"
    EXTRACT_DIR: /usr/share/nginx
    COMPONENT_DIR: /usr/share/nginx/html
    APP_USER: root


- name: move localhost.conf to roboshop.conf
  template:
    src: roboshop.conf
    dest: /etc/nginx/default.d/roboshop.conf

- name: start nginx service
  systemd:
    name: nginx
    state: restarted