- name: install nodejs
  yum:
    name:
      - nodejs
      - make
      - gcc-c++ -y
    state: present

- name: add roboshop user
  include_role:
    name: common
    tasks_from: useradd

- name: Download {{ APP }} component
  include_role:
    name: common
    tasks_from: curl_download
  vars:
    URL: "https://dev.azure.com/DevOps-Batches/f635c088-1047-40e8-8c29-2e3b05a38010/_apis/git/repositories/d62914b9-61e7-4147-ab33-091f23c7efd4/items?path=%2F&versionDescriptor%5BversionOptions%5D=0&versionDescriptor%5BversionType%5D=0&versionDescriptor%5Bversion%5D=master&resolveLfs=true&%24format=zip&api-version=5.0&download=true"
    EXTRACT_DIR: /home/roboshop/catalogue
    APP_USER: roboshop

- name: install NOdeJS module
  community.general.npm:
    path: /home/roboshop/catalogue
  become_user: roboshop

- name: update systemd service files
  ansible.builtin.replace:
    path: /home/roboshop/catalogue/systemd.service
    regexp: 'MONGO_DNSNAME'
    replace: "mongodb-{{ENV}}.devopsproject.tk"

- name: setup systemD script
  shell: mv /home/roboshop/catalogue/systemd.service /etc/systemd/system/catalogue.service

- name: start catalogue service
  systemd:
    name: catalogue
    state: restarted
    enabled: yes
    daemon-reload: yes
