- name: Download {{ component }} component
  ansible.builtin.get_url:
    url: "{{ URL }}"
    dest: /tmp/{{component}}.zip

- name: Remove old content
  ansible.builtin.file:
    path: "{{COMPONENT_DIR}}"
    state: absent

- name: remove old content from nginx
  ansible.builtin.file:
    path: "{{EXTRACT_DIR}}/{{component}}"
    state: absent

#- name: create a directory for {{ component }} component
#  ansible.builtin.file:
#    path: "{{EXTRACT_DIR}}"
#    state: directory
#  become_user: "{{APP_USER}}"

- name: unarchive {{ component }} component
  ansible.builtin.unarchive:
    src: /tmp/{{component}}.zip
    dest: "{{EXTRACT_DIR}}"
    remote_src: yes
  become_user: "{{APP_USER}}"

- name: Move component directory
  shell: mv {{EXTRACT_DIR}}/{{component}}-main {{EXTRACT_DIR}}/{{component}}

- name: Move static content
  shell: mv /usr/share/nginx/frontend /usr/share/nginx/html && mv /usr/share/nginx/html/static/* /usr/share/nginx/html/.
  when: compoent == "frontend"


