- name: install maven
  ansible.builtin.yum:
    name:
      - maven
    state: present

- name: Download {{ component }} component
  ansible.builtin.include_tasks: curl_download.yml
  vars:
    EXTRACT_DIR: /home/roboshop/{{component}}
    APP_USER: roboshop

- name: install maven module
  ansible.builtin.shell: mvn clean package && mv target/shipping-1.0.jar shipping.jar
    args:
      chdir: /home/roboshop/{{component}}
  become_user: roboshop

- name: Download {{ component }} component
  ansible.builtin.include_tasks: systemd.yml

