- name: set hostname for {{component}} component
  shell: set-hostname {{component}}

- name: Add roboshop user
  ansible.builtin.user:
    name: roboshop
  when: APP == "catalogue" or APP == "user" or APP == "cart" or APP == "shipping" or APP == "payment"
  register: out