- name: set hostname for {{APP}} component
  shell: set-hostname {{APP}}

- name: Add roboshop user
  user:
    name: roboshop
  when: APP == "catalogue" or APP == "user" or APP == "cart" or APP == "shipping" or APP == "payment"