- name: install nodejs {{component}} component
  ansible.builtin.yum:
    name:
      - nodejs
      - make
      - gcc-c++
    state: present

- name: Download {{ component }} component
  ansible.builtin.include_tasks: curl_download.yml
  vars:
    EXTRACT_DIR: /home/roboshop
    COMPONENT_DIR: /home/roboshop/{{component}}
    APP_USER: roboshop

- name: install NodeJS module
  #community.general.npm:
  npm:
    path: /home/roboshop/{{component}}
  become_user: roboshop

- name: Download {{ component }} component
  ansible.builtin.include_tasks: systemd.yml
