- name: check if node exporter exists
  stat:
    path: /opt/node_exporter
  register: p

- name: grab latest version
  shell: curl -s  https://github.com/prometheus/node_exporter/releases|grep 1.1.2| grep span| head -1| sed -e 's|>| |g' -e 's|<| |g' | xargs -n1| grep ^v | sed -e 's|v||g'
  register: version

- name: download node exporter
  ansible.builtin.unarchive:
    src: https://github.com/prometheus/node_exporter/releases/download/v{{version.stdout}}/node_exporter-{{version.stdout}}.linux-amd64.tar.gz
    dest: /opt
    remote_src: yes
  when: p.stat.isdir is not defined

- name: rename node_exporter
  shell: mv /opt/node_exporter-{{version.stdout}}.linux-amd64 /opt/node_exporter
  when: p.stat.isdir is not defined

- name: setup node exporter service
  copy:
    src: node_exporter.service
    dest: /etc/systemd/system/node_exporter.service

- name: start node exporter
  systemd:
    name: node exporter
    state: restarted
    enabled: yes
    daemon-reload: yes

