- name: Download {{ component }} component
  include_role:
    name: common
    tasks_from: nodejs
  vars:
    URL: "https://github.com/roboshop-devops-project/cart/archive/main.zip"

- name: setup filebeat
  include_role:
    name: filebeat